### ISSUE TITLE
خطا هنگام Sync اطلاعات

### ISSUE THREAD

**Issue by xJuniorProgrammer** [HosseinShams00/AdobeConnectDownloader#6]
[
![2023-11-19_131831](https://github.com/HosseinShams00/AdobeConnectDownloader/assets/5729722/335e9307-3d0f-4049-af6e-14dd89a42793)
]

سلام بعد دریافت فایل به صورت zip و در مرحله sync به نظرم این اتفاق میفته چون مراحل قبل برنامه سبز است

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')
   at System.String.IndexOf(Char value, Int32 startIndex, Int32 count)
   at AdobeConnectDownloader.Application.FFMPEGManager.GetVideosResolution(String videoAddress, String ffmpegAddress) in C:\My Project\Programing\WinForms\C#\AdobeConnectDownloader\AdobeConnectDownloader\Application\FFMPEGManager.cs:line 129
   at AdobeConnectDownloader.UI.ProcessForm.CheckWebcam(List`1 webcamStreams, String finalAudioAddress, String finalVideoAddress) in C:\My Project\Programing\WinForms\C#\AdobeConnectDownloader\AdobeConnectDownloader\UI\ProcessForm.cs:line 322
   at AdobeConnectDownloader.UI.ProcessForm.<MergeAllFiles>b__75_0() in C:\My Project\Programing\WinForms\C#\AdobeConnectDownloader\AdobeConnectDownloader\UI\ProcessForm.cs:line 272
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at AdobeConnectDownloader.UI.ProcessForm.MergeAllFiles() in C:\My Project\Programing\WinForms\C#\AdobeConnectDownloader\AdobeConnectDownloader\UI\ProcessForm.cs:line 153
   at AdobeConnectDownloader.UI.ProcessForm.ProcessForm_Load(Object sender, EventArgs e) in C:\My Project\Programing\WinForms\C#\AdobeConnectDownloader\AdobeConnectDownloader\UI\ProcessForm.cs:line 76
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)

**Comment by HosseinShams00** [comment]
سلام 
ممنون از اینکه اطلاع دادید 
فایل زیپ مربوطه رو خودتون دستی دانلود کردید یا از طریق برنامه دانلود شده ؟ 
همچنین اگر ممکن هست از داخل اون فایل زیپ یک فایلی هست به اسم 
indexstream.xml 
اونو برام بفرستید ممنون

@xJuniorProgrammer

**Comment by xJuniorProgrammer** [comment]
سلام برنامه خودش دانلود کرد خواست بره مرحله sync خطا داد  
پیوست شد
[indexstream.zip](https://github.com/HosseinShams00/AdobeConnectDownloader/files/13404041/indexstream.zip)

**Comment by HosseinShams00** [comment]
سلام مجدد
من طبق بررسی که کردم اطلاعات فایل ها مشکلی نداره اگر ممکنه خود فایل زیپ اصلی رو برام بفرستید که بتونم کامل تر بررسی کنم 
@xJuniorProgrammer

**Comment by HosseinShams00** [comment]
با سلام با توجه به اینکه پیغامی از شما دریافت نکردم این بخش را میبندم و لطفا در صورتی که مشکل همچنان برقرار بود مشکل را اعلام کنید ممنون

**Comment by xJuniorProgrammer** [comment]
سلام خدمت شما

https://mega.nz/file/uyggUaZL#63FtHdDcz8s7YHEMa1jzGCl5f_uJA65nHs-cza39bk0

**Comment by HosseinShams00** [comment]
سلام آیا از اخرین نسخه برنامه استفاده کرده اید ؟
@xJuniorProgrammer

**Comment by HosseinShams00** [comment]
سلام برنامه به روز رسانی شده و مشکل اعلام شده رو بر طرف کردم .
ممنون میشم از اخرین نسخه استفاده کنید و اگر مشکلی بود اطلاع بدید.
